### ISSUE TITLE
missing plugins

### ISSUE THREAD

**Issue by rmporsch** [eliostvs/tomate-gtk#11]
After installing it on ubuntu 16.04 I cannot find the plug-ins (the list is empty). Do I have to install them somehow separately?

**Comment by eliostvs** [comment]
Yes you have. I'm going to update the docs. Sorry for that. The name of the plugins are: tomate-indicator-plugin, tomate-alarm-plugin, tomate-notify-plugin and tomate-launcher-plugin. Let me know if you still have questions.

**Comment by eliostvs** [comment]
Thank you! I've already merged your pull requests to the develop branch.
