### ISSUE TITLE
May  I seet my music for tomate-alarm-plugin

### ISSUE THREAD

**Issue by krchat** [eliostvs/tomate-gtk#14]
I'd like set any music for this plugin. Is it possible easy? 
And I want to block video output during short break time

**Comment by eliostvs** [comment]
Sorry for the delay. I just updated the alarm-plugin. I'll try to do a release this week.

**Comment by krchat** [comment]
OK. Thanks. I'm waiting for  your new release.

**Comment by eliostvs** [comment]
I did the release yesterday. In the Extension tab now you can choose a custom alarm file.

**Comment by raspatan** [comment]
I confirm that this works flawlessly!

**Comment by eliostvs** [comment]
Great!
