### ISSUE TITLE
Fail to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by andrey-andreev** [eliostvs/tomate-gtk#16]
The installation fails on the last step, here's the error:

`Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/official-toggl/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/official-toggl/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by eliostvs** [comment]
Hi. Have you installed using the [instructions](https://github.com/eliostvs/tomate-gtk#ubuntu-1404)?

**Comment by andrey-andreev** [comment]
Yes

**Comment by AndersonFirmino** [comment]
Same thing with me :s

**Comment by eliostvs** [comment]
Sorry to take so long. I just rebuild the repo. Please try again.

**Comment by raspatan** [comment]
I can install in 16.04 without problems, after most recent fix.

**Comment by eliostvs** [comment]
Great!

**Comment by VictorFursa** [comment]
ubuntu 16.04
W: Репозиторий «http://ppa.launchpad.net/stvs/tomate/ubuntu xenial Release» не содержит файла Release.
E: Не удалось получить http://ppa.launchpad.net/stvs/tomate/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Некоторые индексные файлы не скачались. Они были проигнорированы или вместо них были использованы старые версии.

**Comment by eliostvs** [comment]
Sorry, I can't read what you wrote but I think that you are trying to use the old ppa repository right? You should the new repository: 

```
RELEASE=`sed -n 's/VERSION_ID="\(.*\)"/\1/p' /etc/os-release`
sudo wget -O- http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key | sudo apt-key add -
sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/ ./' > /etc/apt/sources.list.d/tomate.list"
sudo apt-get update && sudo apt-get install tomate-gtk
```

**Comment by raspatan** [comment]
@VictorFursa  That is an **old** repo. Check it [here](http://ppa.launchpad.net/stvs/tomate/ubuntu/dists/). It stopped at Ubuntu Vivid (15.04). Use the one eliostvs is giving you ([this one](http://download.opensuse.org/repositories/home:/eliostvs:/tomate/).
