### ISSUE TITLE
New feature: Pause the timer

### ISSUE THREAD

**Issue by MageJohn** [eliostvs/tomate-gtk#17]
You should be able to pause the timer. Say someone comes and talks to you, or you have to stop working for some other reason, you don't want to count that as work time. Or maybe you want 30 extra seconds of work time, so you pause the break timer. Currently I can't seem to do this. Am I missing something?

**Comment by raspatan** [comment]
Allowing for pauses would necessarily create an incentive to stop it because of non-urgent reasons, missing the whole point of it. I would rather have no pause button.

**Comment by eliostvs** [comment]
As has been said, a pause button could be an incentive to stop a flow for non-urgent reasons I don't plan to add the feature to Tomate.
