### ISSUE TITLE
 Icon scheme

### ISSUE THREAD

**Issue by hughwilliams94** [eliostvs/tomate-gtk#22]
I see that the package comes with a monochrome scheme in the Adwaita folder, but when I use Adwaita as my fallback icon theme (I use KDE with Breeze icons) Tomate does not respect this and simply uses the hicolor theme. Any ideas how to rectify?

**Comment by eliostvs** [comment]
Sorry for the late response. Do you still have this problem?

**Comment by eliostvs** [comment]
Hi, please open another issue if you still have this problem.
