### ISSUE TITLE
Instructions to install from source

### ISSUE THREAD

**Issue by karan-ta** [eliostvs/tomate-gtk#25]
Hello,

I am using fedora 24

could you please give me instructions to install from source ?

i tried :  make 
but installation didnt happen.

please do guide to install from source.

**Comment by eliostvs** [comment]
I think that you could but I don't think that you should install from source. That said if you have native dependencies in your OS, detailed in the [packages](https://github.com/eliostvs/tomate-packages/) repository, you can run `python setup.py install` in the *tomate-gtk* and *tomate* directories. What reasons lead you to install from the source code?

**Comment by karan-ta** [comment]
i wanted to add a feature for personal use.

**Comment by karan-ta** [comment]
adding features like a tasklist.

**Comment by eliostvs** [comment]
If you still have questions, please open a new issue.
