### ISSUE TITLE
windows, osx support ?

### ISSUE THREAD

**Issue by karan-ta** [eliostvs/tomate-gtk#26]
Hi ,

Some of my friends are non linux users.

can i install tomate for them on windows , mac osx ?

gtk does have support across operating systems - so this could be possible.

please guide on installation across windows, mac osx.

**Comment by eliostvs** [comment]
Sorry, this is currently not possible. Tomate depends on Linux DBus.

**Comment by Prikalel** [comment]
> Hi ,
> Some of my friends are non linux users.

karan-ta, if you want you can use just another windows free application like this: https://tomighty.github.io/
