### ISSUE TITLE
Missing repo for Ubuntu 18.04

### ISSUE THREAD

**Issue by michaelhagedon** [eliostvs/tomate-gtk#27]
Using the commands from the README on Ubuntu 18.04, I got the following error for `apt update`:
`E: The repository 'http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.04 ./ Release' does not have a Release file.`

When I manually changed the repo to point at the 17.10 version, I could run tomate again. This sounds similar to #24.

**Comment by eliostvs** [comment]
Sorry, should be available now.
