### ISSUE TITLE
Status Icon doesn't work on Ubuntu 16.04.

### ISSUE THREAD

**Issue by DevotionGeo** [eliostvs/tomate-gtk#29]
Although Indicator Icon works on Ubuntu 16.04, but that's not as cool as the status icon.

**Comment by eliostvs** [comment]
Sorry for the late response. Tomate has a status icon plugin that have the same features and visual of the indicator plugin. One works in the Unity based desktop and the other in Gnome based desktops but I wouldn't say that one is cooler then the other.

**Comment by eliostvs** [comment]
Hi, do you still have this problem?

**Comment by DevotionGeo** [comment]
@eliostvs  Yes, it still doesn't work, and I use Indicator instead.
