### ISSUE TITLE
No module named wiring

### ISSUE THREAD

**Issue by shookees** [eliostvs/tomate-gtk#3]
After the update to 0.4 version via `apt-get upgrade`, tomate stopped working, the run log is as follows:

    $ tomate-gtk
     Traceback (most recent call last):
      File "/usr/bin/tomate-gtk", line 9, in <module>
        load_entry_point('tomate-gtk==0.4.0', 'console_scripts', 'tomate-gtk')()
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
        return ep.load()
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      File "/usr/lib/python3.4/dist-packages/tomate_gtk/__main__.py", line 3, in <module>
        from .main import main
      File "/usr/lib/python3.4/dist-packages/tomate_gtk/main.py", line 8, in <module>
        from tomate.app import Application, ApplicationModule
      File "/usr/lib/python3.4/dist-packages/tomate/app.py", line 4, in <module>
        from wiring import inject, SingletonScope, Module
    ImportError: No module named 'wiring'

Also did a `sudo apt-get install tomate-gtk --reinstall` but without luck the error was the same

**Comment by eliostvs** [comment]
Sorry for that. Which is your distribution/version?

**Comment by Rondo5000** [comment]
I'm experiencing the same issue, and the distribution is in Ubuntu 14.04.  Thanks!

**Comment by shookees** [comment]
Same as Rondo, I'm on Ubuntu 14.04 too

**Comment by link0802** [comment]
I was have same error. As you can see it use Python 3 modules. So be sure to check/install all modules with pip.
For example :
```bash
sudo -H python3.4 -m pip install wiring
```
And etc.

**Comment by eliostvs** [comment]
I think a found the problem. The shebang is wrong in the script `/usr/bin/tomate-gtk`. The script should be run with python 2 but is using python3. This happened because I tried to create packages for python 2 and 3 in the same debian/control. The script is generated by setuptools. For now I will launch a new version only with python2 packages.

**Comment by link0802** [comment]
@eliostvs Thank you!

**Comment by eliostvs** [comment]
I released a new version today. I tested in Ubuntu 14.04 and it worked fine. If you still have problems let me know.

**Comment by shookees** [comment]
It seems that there's no problem (previously removed @link0802's offered solution through pip)
