### ISSUE TITLE
Breaks on debian sid

### ISSUE THREAD

**Issue by TLavocat** [eliostvs/tomate-gtk#30]
Hi, I'm trying to run tomate-gtk on debian sid and I'm getting the following error :

```
python3 tomate_gtk/main.py 
Traceback (most recent call last):
  File "tomate_gtk/main.py", line 14, in <module>
    from tomate.app import Application
ModuleNotFoundError: No module named 'tomate.app'
```

python3 version is 3.6.6

Thanks for your help,
Thomas

**Comment by eliostvs** [comment]
Hi, it seems the package `python-tomate` isn't installed. Could you check that running `dpkg -l | grep python-tomate`?

**Comment by eliostvs** [comment]
If you still have problems, please open a new issue.
