### ISSUE TITLE
Fedora 29 package: 3.6 ABI compliance

### ISSUE THREAD

**Issue by psukys** [eliostvs/tomate-gtk#31]
Since Fedora 29 packs with Python 3.7, and `tomate-gtk` package require 3.6 ABI, the package can't be installed.

Repository used ([source](https://software.opensuse.org/download.html?project=home%3Aeliostvs%3Atest&package=tomate-gtk)):
```
https://download.opensuse.org/repositories/home:eliostvs:test/Fedora_25/home:eliostvs:test.repo
```

Error when trying to install:
```
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.6 needed by tomate-gtk-0.8.0-27.1.noarch
```

**Comment by eliostvs** [comment]
Thanks for reporting. I'm not referencing the version 3.6 directly as far as I know. The packages metadata is in [this](https://github.com/eliostvs/tomate-packages) repository. I'll review the fedora metadata file. Help is welcome.

**Comment by psukys** [comment]
I'm not familiar with OpenSUSE build service, but maybe the build was packaged against repository's provided packages? i.e. python3 being strictly resolved to 3.6 and so on.
Would adding Fedora 28 and 29 resolve this?

**Comment by psukys** [comment]
@eliostvs I think it might just be that tomate just needs to be packaged against Fedora's version. From what I could tell

**Comment by eliostvs** [comment]
I've stop to build python 2 packages of a dependency (wiring) and enabled the build for the fedora 28 and 29. It seems that is working. At least I was able to install tomate-gtk in a docker image. Could you try again?

**Comment by psukys** [comment]
Yes! The packages are there, thanks!
