### ISSUE TITLE
Accessibility: add accelerator (shortcut) keys

### ISSUE THREAD

**Issue by psukys** [eliostvs/tomate-gtk#32]
A minor feature, but rather convenient. When a pomodoro ends, I just want to start the 5-minuter, but have to drag the mouse to start it, when instead there could be a shortcut to start the timer

**Comment by eliostvs** [comment]
Hi, I did a release today, 0.11.0, that add shortcuts to start (control + s), stop (control + p) and reset (control + r) sessions. You can not change the shortcuts yet.
