### ISSUE TITLE
Starting a break says "time to work"

### ISSUE THREAD

**Issue by vsund** [eliostvs/tomate-gtk#33]
No big thing, just noticed that when starting the timer for a break the notification says "It's time to work.". Might be a quick fix. Got a little bit confused :)

**Comment by eliostvs** [comment]
I did a release that should fix this. You need to update python-tomate, tomate-gtk and the plugin. Let me known if you still have a problem.

**Comment by vsund** [comment]
Works perfectly. Thanks a lot!
