### ISSUE TITLE
apt key expired

### ISSUE THREAD

**Issue by dvolpato** [eliostvs/tomate-gtk#38]
After following the installation instructions for Ubuntu (my release is 18.04), I'm getting the following error when running apt update:

`W: GPG error: http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.04 ./ Release: The following signatures were invalid: EXPKEYSIG 3126A3438CA9B269 home:eliostvs OBS Project <home:eliostvs@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.04 ./ Release' is not signed.`

It seems the key has expired and needs to be updated.

**Comment by eliostvs** [comment]
Hi, I rebuilt the repo. Please try again.

**Comment by tacubaya** [comment]
Hi. I have the same problem. Seems like the repository for Ubuntu 18.04 is gone. http://download.opensuse.org/repositories/home:/eliostvs:/tomate/

**Comment by eliostvs** [comment]
I rebuilt all Ubuntu repositories. Please try again.

**Comment by tacubaya** [comment]
Just retried, same problem.

<pre>W: GPG error: http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.04 ./ InRelease: The following signatures were invalid: EXPKEYSIG 3126A3438CA9B269 home:eliostvs OBS Project &lt;home:eliostvs@build.opensuse.org&gt;
E: The repository &apos;http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.04 ./ InRelease&apos; is not signed.
</pre>

**Comment by eliostvs** [comment]
I rebuilt the repository and tested the installation in a docker container. Should be working now.

**Comment by dvolpato** [comment]
> Hi, I rebuilt the repo. Please try again.

Worked for me. Thx

**Comment by rahimratnani** [comment]
Hi. I'm using Ubuntu 21.10 and facing the same issue as @dvolpato.

**Comment by MrUnfunny** [comment]
Hi. I'm getting a similar issue.
`
GPG error: http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_20.04 ./ InRelease: The following signatures were invalid: EXPKEYSIG 3126A3438CA9B269 home:eliostvs OBS Project <home:eliostvs@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_20.04 ./ InRelease' is not signed.
`

**Comment by eliostvs** [comment]
Hi, I just rebuilt the repositories. Could you try again?

**Comment by rahimratnani** [comment]
It worked. Thanks.

**Comment by eliostvs** [comment]
Great!
