### ISSUE TITLE
tomate-gtk on Elementary OS Luna

### ISSUE THREAD

**Issue by VitalikOrlioglo** [eliostvs/tomate-gtk#4]
Hi
I am trying to install tomate-gtk for elementary OS Luna 0.2.1
When i run this command:
`sudo wget -O- http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key | sudo apt-key add - sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/ ./' > /etc/apt/sources.list.d/tomate.list"`
it gives me an error:
`gpg: no valid OpenPGP data found.`
I don't know what is gpg, and how to resolve this issue.
It's some issue or i am doing something wrong?

**Comment by VitalikOrlioglo** [comment]
I understood that this error was because of variable $RELEASE
`RELEASE=sed -n 's/VERSION_ID="\(.*\)"/\1/p' /etc/os-release`
In my case, it's was 0.2.1
I put in variable RELEASE = 14.04
`RELEASE='14.04'`
download Release.key and put deb in tomate.list
`sudo wget -O- http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key | sudo apt-key add - sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/ ./' > /etc/apt/sources.list.d/tomate.list"`
and then:
`sudo apt-get update && sudo apt-get install tomate-gtk`
it gives me error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tomate-gtk : Depends: python-tomate (>= 0.5.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

And just in case i try to install python-tomate
`sudo apt-get install python-tomate`
but ineffectually:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-tomate : Depends: python-enum34 but it is not installable
                 Depends: python-yapsy but it is not installable
E: Unable to correct problems, you have held broken packages.

As I understand it this is due to incompatibility, yeah?
Although, old version from https://launchpad.net/tomate is installing properly

upd2: and yeah, i have removed old version before to install this version

**Comment by eliostvs** [comment]
Hi, I was able to install tomate in a clean installation of Elementary OS 0.3.2 in a VM. I set the variable RELEASE to 14.04 as you.  Have you tried to remove the old repository from your sources?

**Comment by VitalikOrlioglo** [comment]
Sorry for late answer
Yeah, at first i have purged tomate
`sudo apt-get purge tomate`
second, i have removed repository
`sudo add-apt-repository --remove ppa:stvs/tomate`
and check in synaptic
next, i download Release.key and put deb in tomate.list
`sudo wget -O- http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_14.04/Release.key | sudo apt-key add - sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_14.04/ ./' > /etc/apt/sources.list.d/tomate.list"`
answer from terminal
`--2016-03-01 13:43:42--  http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_14.04/Release.key
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1102 (1.1K) [application/pgp-keys]
Saving to: `STDOUT'

100%[================================================================================================================================>] 1,102       --.-K/s   in 0s      

2016-03-01 13:43:42 (111 MB/s) - written to stdout [1102/1102]

OK
`

and with command 
`sudo apt-get install tomate-gtk`
get error
`The following packages have unmet dependencies:
 tomate-gtk : Depends: python-tomate (>= 0.5.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by VitalikOrlioglo** [comment]
And i think, problem in incompatibility
Elementary OS Luna(from version 0.2 and next) based on Ubuntu 12.04
Elementary OS Freya(from version 0.3 and next) based on Ubuntu 14.04

**Comment by eliostvs** [comment]
Hi. I did some tests and I got the same conclusion as you. The packages in Luna are too old. Although will work on Freya. Sorry for the late answer.
