### ISSUE TITLE
tomate-statusicon-plugin doesn't work (ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by brainbow1** [eliostvs/tomate-gtk#40]
Hello!
Thank you for ur work, it is pretty amazing what simple and efficient tool u've built here!
I installed the "tomate-statusicon-plugin" and activated it in the preferences, but unfortunately it doesn't work under my ubuntu 20.04 LTS system.. 
Are there any recommendations what I can do, or is it a unfixed bug?
If so, I would highly appreciate when that works, as this function was the main reason for  me to get this amazing tool!
happy about ur answer
best regards
Matt

**Comment by brainbow1** [comment]
I am also willing to do a donation for this to work! I highly appreciate ur work!

**Comment by eliostvs** [comment]
Which desktop environment are you using? Gnome 3?

**Comment by brainbow1** [comment]
Thank u for ur answer!
Yes, I am using GNOME 3.36.2 and ubuntu 20.04LTS.
I am using the Dash-To-Panel extension here: https://extensions.gnome.org/extension/1160/dash-to-panel/

At the bottom right-hand side, there are shown my other status icons like vlc player (when its open), seafile client tray icon and so on... But Tomate is only shown in the bottom menu, as long as its open... when i close tomate, it is neither in the apllicationsbar, nor in the statusbar... but its running and alarming and so on.. so generally its working.. but its not so good to not see the progress of the timer in the status bar :(
I attached a screenshot which shows my panel while tomate is open..maybe that helps..
![Bildschirmfoto von 2020-05-26 18-19-30](https://user-images.githubusercontent.com/61545653/82925228-baaf4b00-9f7d-11ea-92f8-c81c0f9152eb.png)

**Comment by eliostvs** [comment]
I don't think StatusIcon will work in the Gnome 3 anymore. Probably the solution is create a new plugin implementing [StatusNotififerItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) specification. I will start to explore this alternative.

**Comment by brainbow1** [comment]
Thanks a lot for ur answer and ur effort!
I would highly appreciate if that amazing tool is working under gnome 3..am sure that lots of other users will love it, too :-) Please keep me up to date if there are any fixes for this!

**Comment by eliostvs** [comment]
After almost two years, I released the [StatusNotifierItem plugin](https://github.com/eliostvs/tomate-statusnotifieritem-plugin) yesterday. Sorry for the late response.
