### ISSUE TITLE
openSuse repo not available

### ISSUE THREAD

**Issue by athyla** [eliostvs/tomate-gtk#42]
Hello!

The repo for openSuse is not available anymore for stable.
I've tried the test repo, however dependencies cannot be resolved (Problem: nothing provides python(abi) = 3.7 needed by tomate-gtk-0.11.0-41.1.noarch).

**Comment by eliostvs** [comment]
Hi. I enabled the openSUSE Tumbleweed, Leap_15.1 and Leap_15.2 repositories. Could you test again?

**Comment by athyla** [comment]
Great! It works as expected now, thanks!
Just for the record, I am on Tumbleweed.

**Comment by eliostvs** [comment]
Glad to known.
