### ISSUE TITLE
Error cannot import name 'BaseDirectory' from 'xdg' 

### ISSUE THREAD

**Issue by ad1cted** [eliostvs/tomate-gtk#44]
this error happens on Ubuntu 21.04  and can be solved installing  pyxdg==0.25
 
 with : 
 ` pip install pyxdg==0.25`

**Comment by eliostvs** [comment]
Hi. *tomate-gtk* depends on *python3-xdg* on Ubuntu. Did you install tomate from the [repository](https://github.com/eliostvs/tomate-gtk#ubuntu-2004)? If so, could you confirm that the package *python3-xdg* is installed?

**Comment by ad1cted** [comment]
I have installed it from repositories, the error occurs in ubuntu 21.04 with the python version that forces to install pyxdg in its latest version but this is not supported by tomato-gtk

**Comment by eliostvs** [comment]
I tested it on a clean and updated Ubuntu 21.04 virtual machine and had no problems. The *python3-xdg* is the native package of *pyxdg*. The tomate-gtk package metadata was wrong for some time, maybe you have a bad version. You can execute the command `apt show tomate-gtk | grep Depends` and check if *python3-xdg* is listed.

**Comment by eliostvs** [comment]
Hi, Do you still have problems?

**Comment by eliostvs** [comment]
Please open a new issue if you still have problems.
