### ISSUE TITLE
System tray icon missing (Ubuntu 14.04)

### ISSUE THREAD

**Issue by woodyrew** [eliostvs/tomate-gtk#5]
I've tried [tomate-indicator-plugin](https://github.com/eliostvs/tomate-indicator-plugin) and [tomate-statusicon-plugin](https://github.com/eliostvs/tomate-statusicon-plugin) without success. Is there something specific that I need to do?

**Comment by rogerkk** [comment]
FWIW, I have the same problem in Ubuntu 16.04.

Wonder if this has something to do with Ubuntu's handling of the system tray? See for example this post: https://bugs.launchpad.net/ayatana-design/+bug/974480. Not sure if this means that Tomate would need to support some kind of application indicator system that Unity offers.

Sorry I can't offer more useful input here, but I just don't have time to start digging atm.

**Comment by eliostvs** [comment]
Hi. I did a new release of the tomate-indicator-plugin (0.7.0). I will treat this problem in the [tomate-indicator-plugin issue page](https://github.com/eliostvs/tomate-indicator-plugin/issues/3). Could you try again and write the result there? Thank you.
