### ISSUE TITLE
Depends: python-tomate (>= 0.13.0) but it is not installable

### ISSUE THREAD

**Issue by sontranchuhung** [eliostvs/tomate-gtk#54]
When I run "sudo apt-get install tomate-gtk" got this error:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tomate-gtk : Depends: python-tomate (>= 0.13.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

Im currently running Ubuntu 22.04.3 LTS.
"sudo apt --fix-broken install" was not resolving any package and there is no held package with "dpkg --get-selections | grep hold"

**Comment by eliostvs** [comment]
Hi, please update your repositories and try installing again. The dependency python-tomate is deprecated. I've stopped building it, but have not yet removed it from the tomate-gtk package metadata.

**Comment by sontranchuhung** [comment]
I ran the following commands: 'sudo apt-get remove tomate-gtk,' 'sudo apt-get autoremove,' with updating and upgrading the APT package manager. After that, I installed again and it worked as expected. Thank you for your assistance.
