### ISSUE TITLE
Wrong repository url for Debian installation in README

### ISSUE THREAD

**Issue by SaltyPretzel303** [eliostvs/tomate-gtk#55]
> curl -fsSL "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tomate.gpg > /dev/null
> echo "deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/ ./" | sudo tee /etc/apt/sources.list.d/tomate.list

In urls in these two lines xUbuntu should be replaced with Debian.

**Comment by eliostvs** [comment]
Thank you for informing me. The link has been fixed.
