### ISSUE TITLE
Ubuntu repository URLs not working

### ISSUE THREAD

**Issue by loheander** [eliostvs/tomate-gtk#56]
Hi!

The URLs listed in the README.md file doesn't work anymore. I tried to browse around and find the correct path myself, but even after trying `https://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04/`, I still get signing problems:

```
E: The repository 'https://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04 jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04 ./ InRelease: The following signatures were invalid: EXPKEYSIG 3126A3438CA9B269 home:eliostvs OBS Project <home:eliostvs@build.opensuse.org>
```

Like the software and use it a lot, so don't want to remove the repo just to make my `apt update` start working again.

Best regards!
Lo

**Comment by eliostvs** [comment]
Hello, APT has changed its method for managing GPG keys. So, you may need to delete the old key and download the new one.

As sudo:

```bash
apt-key del DCF5D0463AE99F529DDDF0B23126A3438CA9B269
curl -fsSL "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04/Release.key" | gpg --dearmor | tee /etc/apt/trusted.gpg.d/tomate.gpg > /dev/null
echo "deb [signed-by=/etc/apt/trusted.gpg.d/tomate.gpg] http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04/ ./" > /etc/apt/sources.list.d/tomate.list
```

**Comment by brendonwp** [comment]
Hi there, I've just upgraded to Ubuntu 24.04 and tried the listed instructions on this site (replacing RELEASE with 24.04). I get "Permission denied".  
Thanks!

See below:

```
sudo curl -fsSL "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_24.04/Release.key" | gpg --dearmor | tee /etc/apt/trusted.gpg.d/tomate.gpg > /dev/null
tee: /etc/apt/trusted.gpg.d/tomate.gpg: Permission denied
```

**Comment by eliostvs** [comment]
Hi, please follow the [Ubuntu installation instrunctions](https://github.com/eliostvs/tomate-gtk?tab=readme-ov-file#ubuntu-2004). It is more accurate than my example above.

 In the command above you need root permissions to write the file, so the command should be `curl -fsSL "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_24.04/Release.key" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tomate.gpg > /dev/null`.
