### ISSUE TITLE
There is no working repository for Fedora

### ISSUE THREAD

**Issue by Kasmetski** [eliostvs/tomate-gtk#9]
[***@****** pomodoro]# sudo dnf config-manager --add-repo http://download.opensuse.org/repositories/home:/eliostvs:/tomate/Fedora_$RELEASE/home:eliostvs:tomate.repo
Adding repo from: http://download.opensuse.org/repositories/home:/eliostvs:/tomate/Fedora_24/home:eliostvs:tomate.repo
**Status code: 404 for http://download.opensuse.org/repositories/home:/eliostvs:/tomate/Fedora_24/home:eliostvs:tomate.repo**

**Comment by Kasmetski** [comment]
I found the problem. Just there is no repository for the newest version of Fedora (24), after I changed the path to 
`http://download.opensuse.org/repositories/home:/eliostvs:/tomate/Fedora_23/home:eliostvs:tomate.repo`

everything worked fine

**Comment by eliostvs** [comment]
I added the Fedora 24 repository. It should be working know. Thanks for the report.
